### ISSUE TITLE
We should add the previous sections as files to this repo

### ISSUE THREAD

**Issue by amsos** [Govrn-HQ/white-paper#15]
**Comment Description**
While the first sections we wrote we collabed using google docs, we've enjoyed using github so far.  We should add those as files to this github repo.

**Referred to Section**
N/A

**Why is this a concern**
Having all of our white paper sections in one place would be a huge value add and time saver.  Trying to click around to find them is no fun 😤

**Preferred Langauge**
N/A

**Suggested Section**
N/A

**Comment by christinevandev** [comment]
Done!
